[package]
name = "eigen-client"
description = "Eigen Client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio-stream = "0.1.16"
rust-kzg-bn254 = "0.2.1"
ark-bn254 = "0.5.0"
num-bigint = "0.4.6"
serial_test = "3.1.1"
rlp = "0.5"
rand = "0.8"
sha3 = "0.10.8"
tiny-keccak = "2"
ethabi = "18.0.0"
thiserror = "1"
ethereum-types = { version = "0.14.1", features = ["serialize"] }
prost = "0.12.6"
tonic = { version = "0.11.0", features = ["tls-roots", "prost", "codegen"] }
secp256k1 = { version = "0.27.0", features = ["recovery", "global-context"] }
subxt-signer = { version = "0.34", features = ["sr25519", "native"] }
bytes = {version= "1", features = ["serde"]}
reqwest = {version = "0.12", features = ["json"] }
serde = "1"
serde_json = "1"
backon = "0.4.4"
tokio = "1"
async-trait = "0.1"
hex = "0.4"
secrecy = "0.8.0"
byteorder = "1.5.0"
url = "2.5.4"
